-- ============================================================
-- StarzLink: Real Opportunity Data Seed
-- Researched: Liberia, West Africa, and US opportunities
-- that directly benefit Liberians and West Africans
-- ============================================================

-- ─── INTERNSHIPS ─────────────────────────────────────────────────────────────
INSERT INTO opportunities (opportunity_type, title, organizer, category, description, location, is_remote, deadline, application_link, eligibility, benefits, duration, stipend, status) VALUES

('internship', 'USAID Liberia – Youth in Agriculture Internship',
 'USAID Liberia / Feed the Future Program',
 'Agriculture & Food Security',
 'USAID's Feed the Future initiative offers youth internships in agricultural development, rural finance, and food security projects across Liberia. Interns work alongside USAID staff and implementing partners to support field programs, data collection, and community engagement in counties including Bong, Nimba, and Lofa. Strong candidates will gain hands-on experience in agricultural value chains, smallholder farmer support, and international development programming.',
 'Monrovia, Liberia', false,
 '2026-06-30',
 'https://www.usaid.gov/liberia',
 E'• Liberian nationals aged 18-35\n• Enrolled in or recently graduated from an agriculture, economics, or development-related program\n• Strong communication skills in English\n• Ability to travel to project counties',
 E'• Monthly stipend of $300\n• Professional mentorship from USAID staff\n• Exposure to international development methods\n• Certificate of completion\n• Potential pathway to full employment',
 '3-6 months', '$300/month', 'active'),

('internship', 'United Nations System – Liberia Internship Programme',
 'United Nations (UNDP, UNICEF, WFP, UN Women – Liberia)',
 'International Development',
 'Multiple United Nations agencies operating in Liberia offer internship opportunities for students and recent graduates. Agencies including UNDP, UNICEF, WFP, and UN Women place interns in departments covering governance, child protection, humanitarian affairs, gender equality, and economic development. Interns gain direct exposure to the UN's work in post-conflict stabilization, Sustainable Development Goals (SDG) programming, and multilateral diplomacy in Liberia.',
 'Monrovia, Liberia', false,
 '2026-07-31',
 'https://careers.un.org/lbw/jobdetail.aspx?id=internship',
 E'• Enrolled in a graduate or undergraduate program (or graduated within 12 months)\n• Liberian nationals or international candidates welcome\n• Minimum GPA of 3.0 or equivalent\n• Fluency in English required\n• Specialized skills depending on department (IT, communications, finance, public health)',
 E'• Monthly living allowance (varies by agency)\n• UN system networking and mentorship\n• Access to UN learning and certification programs\n• Formal reference letters\n• Priority consideration for future UN vacancies',
 '2-6 months', 'Allowance provided', 'active'),

('internship', 'African Development Bank – Young Professionals Programme',
 'African Development Bank (AfDB)',
 'Finance & Economic Development',
 'The AfDB Young Professionals Program is a highly competitive entry-level program designed to attract talented young Africans to the Bank. YPPs spend two years rotating through different departments including Infrastructure, Agriculture, Private Sector, and Finance, gaining broad exposure to development finance across Africa. Liberian graduates with strong academic records and commitment to African development are strongly encouraged to apply.',
 'Abidjan, Côte d''Ivoire', false,
 '2026-09-30',
 'https://www.afdb.org/en/careers/young-professionals-program',
 E'• African citizen under 32 years of age\n• Master''s degree or PhD in economics, finance, engineering, or a related field\n• At least 3 years of relevant work experience\n• Strong analytical skills and fluency in English or French\n• Commitment to Africa''s development',
 E'• Competitive international salary\n• Comprehensive benefits package\n• Rotation across AfDB departments\n• Professional development and training\n• Potential for permanent employment after 2 years',
 '2-year rotational program', 'Competitive salary', 'active'),

('internship', 'ECOWAS Commission – Youth Internship Programme',
 'Economic Community of West African States (ECOWAS)',
 'Regional Integration & Policy',
 'ECOWAS offers structured internship opportunities for young West Africans within its Commission headquarters in Abuja and regional offices. Interns work in departments including Trade, Customs, Political Affairs, Humanitarian Affairs, and Communications. This is an outstanding opportunity for Liberian students to engage with regional policy, cross-border trade, and West African integration at the highest institutional level.',
 'Abuja, Nigeria / Regional Offices', false,
 '2026-08-15',
 'https://www.ecowas.int/careers/',
 E'• Citizen of an ECOWAS member state (including Liberia)\n• Currently enrolled in a university or recently graduated (within 2 years)\n• Minimum GPA of 3.0 or equivalent\n• Strong written and verbal communication skills\n• Proficiency in English, French, or Portuguese',
 E'• Monthly stipend (ECO allowance)\n• Direct exposure to regional governance and policy\n• Networking across West African institutions\n• Official ECOWAS internship certificate\n• Travel and accommodation assistance',
 '3-6 months', 'Monthly allowance', 'active'),

('internship', 'Ellen Johnson Sirleaf Presidential Center – Internship',
 'EJC Center for Women and Peace, Monrovia',
 'Leadership & Peacebuilding',
 'The Ellen Johnson Sirleaf Presidential Center for Women and Peace (EJC), established by Africa''s first female president and Nobel Peace Prize laureate, offers internships to passionate young Liberians committed to peace, gender equality, and leadership development. Interns support research, program coordination, and events at the center, gaining unique access to national and international networks for women''s empowerment and peacebuilding.',
 'Monrovia, Liberia', false,
 '2026-05-31',
 'https://www.ejcenter.org/opportunities',
 E'• Liberian nationals preferred\n• Currently enrolled in university (any field) or recently graduated\n• Passion for gender equality, peace, and leadership\n• Strong writing and research skills\n• Previous community service or volunteer experience an advantage',
 E'• Unique mentorship in peacebuilding and leadership\n• Access to high-level networks and events\n• Formal certificate from a Nobel Peace Prize laureate''s institution\n• Professional writing and communications experience\n• Reference letter from EJC leadership',
 '3-6 months', 'Volunteer/Stipend', 'active'),

('internship', 'Google Africa Developer Scholarship – Internship Pathway',
 'Google / Andela / ALX Africa',
 'Technology & Software Development',
 'Through partnerships with Andela and ALX Africa, Google offers virtual internship and scholarship pathways for African developers including Liberians. The program covers Android development, web technologies, UX design, and cloud computing. Participants access Google-quality curriculum, mentorship, and real project experience. Top performers are eligible for Google-sponsored internship placements at tech companies across Africa and globally.',
 'Remote / Online', true,
 '2026-09-15',
 'https://developers.google.com/africa',
 E'• Open to all African nationals including Liberians\n• Age 18-35\n• Basic computer literacy and internet access\n• English proficiency\n• Commitment to complete 6-month program (10-15 hours/week)\n• No prior programming experience required for beginner track',
 E'• Free Google-quality technical training\n• Internship placement opportunities\n• Google Developer certification\n• Access to global tech network\n• Job placement support through Andela/ALX network',
 '6 months', 'Stipend for top performers', 'active');

-- ─── GRANTS & FELLOWSHIPS ────────────────────────────────────────────────────
INSERT INTO opportunities (opportunity_type, title, organizer, category, description, location, is_remote, deadline, application_link, eligibility, benefits, amount, status) VALUES

('grant', 'Tony Elumelu Foundation Entrepreneurship Programme',
 'Tony Elumelu Foundation (TEF)',
 'Entrepreneurship & Business',
 'The Tony Elumelu Foundation Entrepreneurship Programme is Africa''s largest entrepreneurship programme, providing $5,000 non-refundable seed capital, 12 weeks of business training via the TEF Entrepreneurship Programme online platform, and mentorship to 1,000 African entrepreneurs annually. Since 2015, TEF has empowered over 18,000 African entrepreneurs across all 54 African countries including Liberia. The programme is a powerful catalyst for Liberian entrepreneurs with viable business ideas.',
 'Pan-African (All 54 Countries)', true,
 '2026-03-31',
 'https://tefconnect.com',
 E'• African citizen (including Liberian nationals)\n• Age 18-35\n• Business idea or early-stage startup (maximum 3 years old)\n• Commitment to complete the 12-week online training program\n• Business must be based and operational in Africa',
 E'• $5,000 non-refundable seed capital\n• 12-week business training on the TEF platform\n• One-on-one mentorship from business professionals\n• Lifetime access to the TEF alumni network (18,000+ entrepreneurs)\n• Business plan development support',
 '$5,000 seed capital', 'active'),

('grant', 'Mandela Washington Fellowship for Young African Leaders (YALI)',
 'U.S. Department of State / IREX',
 'Leadership & Public Policy',
 'The Mandela Washington Fellowship is the flagship program of the U.S. Young African Leaders Initiative (YALI), offering young African leaders the opportunity to hone their skills at a U.S. university and engage with American institutions, organizations, and communities. Fellows participate in a 6-week Leadership Institute at U.S. universities, followed by a summit in Washington D.C. and optional professional development experiences. This program is fully funded by the U.S. government and is specifically designed to strengthen Liberia''s next generation of leaders.',
 'United States (Various Universities)', false,
 '2026-11-01',
 'https://yali.state.gov/washington-fellowship',
 E'• Sub-Saharan African citizen aged 25-35\n• Demonstrated leadership experience in Business, Civic Engagement, or Public Management\n• Commitment to return to and improve their home country after the fellowship\n• English proficiency\n• Not a current U.S. citizen or permanent resident',
 E'• Fully funded travel (flights, accommodation, meals)\n• 6-week intensive institute at a top U.S. university\n• Washington D.C. Presidential Summit with U.S. government officials\n• Access to the YALI Network (500,000+ African leaders)\n• Lifetime alumni community and professional network',
 'Fully funded (all expenses)', 'active'),

('grant', 'Hubert H. Humphrey Fellowship Program',
 'U.S. Department of State / IIE',
 'Professional Development & Public Policy',
 'The Hubert H. Humphrey Fellowship Program brings accomplished mid-career professionals from developing countries to the United States for 10 months of non-degree graduate study and professional development. Liberian professionals in public health, journalism, law, education, economic development, and environmental policy can apply. Fellows affiliate with a U.S. university, participate in professional development activities, and establish lasting ties with American counterparts.',
 'United States (Various Universities)', false,
 '2026-09-15',
 'https://www.humphreyfellowship.org',
 E'• Liberian (or other developing country) citizen\n• Mid-career professional with a minimum of 5 years of experience\n• Demonstrated leadership qualities\n• English proficiency (TOEFL or IELTS scores)\n• Not a current U.S. citizen, resident, or recent U.S. student',
 E'• Fully funded 10-month program\n• University affiliation and non-degree study\n• Professional development activities and site visits\n• Round-trip international airfare and housing\n• Monthly stipend for living expenses\n• Access to extensive U.S. alumni network',
 'Fully funded fellowship', 'active'),

('grant', 'African Women''s Development Fund (AWDF) Grants',
 'African Women''s Development Fund (Accra, Ghana)',
 'Women''s Empowerment & Human Rights',
 'The African Women''s Development Fund (AWDF) is a pan-African grant-making foundation that funds African women''s organizations working across the continent. AWDF provides grants to organizations in Liberia and across sub-Saharan Africa working on women''s rights, leadership, health, economic empowerment, and conflict transformation. Liberian women-led organizations and NGOs are particularly encouraged to apply.',
 'Sub-Saharan Africa (Pan-African)', false,
 '2026-06-30',
 'https://www.awdf.org/grants',
 E'• Women-led African organization registered in Africa\n• Working on women''s rights, health, empowerment, or peacebuilding\n• At least 1 year operational history with financial records\n• Clear program objectives and measurable outcomes\n• Organizations in Liberia strongly encouraged to apply',
 E'• Grants ranging from $5,000 to $50,000\n• Capacity-building support and training\n• Access to AWDF''s pan-African network\n• Organizational visibility and credibility\n• Potential for multi-year funding',
 '$5,000 - $50,000', 'active'),

('grant', 'Echoing Green Fellowship',
 'Echoing Green Foundation (USA)',
 'Social Entrepreneurship & Innovation',
 'Echoing Green''s Fellowship identifies, invests in, and supports bold new social entrepreneurs committed to changing the world. Since 1987, Echoing Green has supported nearly 1,000 social entrepreneurs and their organizations, providing early-stage risk capital and two years of support. The fellowship seeks leaders who are developing transformative ideas to address inequity across Liberia, West Africa, and the world. Liberian social innovators have a strong track record with Echoing Green.',
 'Global (US-based foundation)', true,
 '2026-01-15',
 'https://echoinggreen.org/fellowship',
 E'• Working on a new social enterprise addressing systemic inequity\n• In early stages (idea to 3 years old)\n• Available to commit full-time to the venture\n• Open to all nationalities including Liberians\n• Strong personal story of leadership and resilience',
 E'• $90,000 stipend over 2 years ($45,000/year)\n• Health insurance and professional development budget\n• Access to Echoing Green''s global network\n• Media visibility and press support\n• Annual Fellows Summit in New York',
 '$90,000 over 2 years', 'active'),

('grant', 'Ford Foundation International Fellowships Program (IFP)',
 'Ford Foundation (New York, USA)',
 'Higher Education & Social Justice',
 'The Ford Foundation International Fellowships Program supports individuals who demonstrate exceptional promise to become leaders in their respective fields and in their societies. IFP provides support for up to 3 years of formal graduate-level study. The program is committed to supporting individuals from social groups that have lacked systematic access to higher education, particularly those from marginalized communities in Liberia, West Africa, and other developing regions.',
 'Global (study anywhere)', true,
 '2026-12-01',
 'https://www.fordfoundation.org/work/learning-and-impact/ford-fellows',
 E'• From a historically marginalized or underrepresented community\n• Demonstrated commitment to social change in your home country\n• Ready to pursue graduate study (master''s or doctoral)\n• Strong academic record\n• Commitment to return to your home region after studies',
 E'• Full tuition and educational expenses for up to 3 years\n• Monthly stipend for living expenses\n• Round-trip international travel\n• Health insurance\n• Access to Ford Foundation''s global alumni network (4,500+ fellows)',
 'Up to $50,000/year (full funding)', 'active');

-- ─── COMPETITIONS & AWARDS ───────────────────────────────────────────────────
INSERT INTO opportunities (opportunity_type, title, organizer, category, description, location, is_remote, deadline, application_link, eligibility, benefits, prize, team_size, status) VALUES

('competition', 'Anzisha Prize – Africa''s Youngest Entrepreneurs',
 'African Leadership Academy (ALA)',
 'Youth Entrepreneurship',
 'The Anzisha Prize is an annual continental award celebrating Africa''s very youngest entrepreneurs — those aged 15 to 22 — who are creating solutions to problems in their communities and countries. Named after an ancient African word for "the one who shows the way," the prize aims to show that exceptional entrepreneurs can come from anywhere, including rural Liberia. Past winners have built businesses in agribusiness, education technology, healthcare, and clean energy.',
 'Pan-African (Johannesburg-based)', true,
 '2026-06-15',
 'https://anzishaprize.org',
 E'• African citizen aged 15-22\n• Running a business for at least 1 year\n• Business is generating some revenue or clear social impact\n• Business is based in Africa\n• Liberian youth entrepreneurs strongly encouraged',
 E'• Up to $25,000 in prize money for top winners\n• Business development support and mentorship\n• Media coverage across Africa\n• Connection to African Leadership Academy alumni network\n• Access to investor networks',
 'Up to $25,000', '1-2 founders', 'active'),

('competition', 'Hult Prize – World''s Largest Student Competition',
 'Hult International Business School',
 'Social Enterprise & Innovation',
 'The Hult Prize is the world''s largest student competition, challenging university students to develop innovative social enterprises that address the world''s most pressing issues. Each year focuses on a theme — past themes include food security, urban youth unemployment, and early childhood education. With a top prize of $1 million and 800+ campus competitions globally, Liberian university students can compete at their own institutions or regional rounds. Multiple West African teams have reached the global finals.',
 'Global (800+ campuses + Regional rounds)', true,
 '2026-10-31',
 'https://hultprize.org',
 E'• Currently enrolled university student (full or part-time)\n• Team of 3-4 students (no age limit)\n• Business idea must address the annual Hult Prize challenge\n• Open to all nationalities including Liberians\n• Must compete through a university campus round or regional accelerator',
 E'• $1,000,000 for global winner\n• Regional prizes of $10,000-$50,000\n• Access to Hult Prize accelerator program\n• Mentorship from global business leaders\n• International media exposure',
 '$1,000,000 global prize', '3-4 students', 'active'),

('competition', 'MIT Solve – Global Challenges Competition',
 'Massachusetts Institute of Technology (MIT)',
 'Technology & Innovation',
 'MIT Solve is a marketplace for social impact innovation. Each year, Solve identifies tech-based challenges in four pillars: Health, Education, Economic Prosperity, and Environment. Solvers who win receive financial awards and 18 months of dedicated support to accelerate their work. The program has supported dozens of African innovators and explicitly seeks solutions from underrepresented regions including Liberia and West Africa.',
 'Global (USA-based)', true,
 '2026-03-31',
 'https://solve.mit.edu',
 E'• Open to individuals and teams globally including Liberians\n• Working on a technology-driven solution to a global challenge\n• Early to growth stage (proof of concept or beyond)\n• No age or educational requirement\n• Must be able to present in English',
 E'• $10,000 - $150,000 in solver awards\n• 18-month intensive support from MIT ecosystem\n• Access to MIT Solve''s global community\n• Connection to technology investors and partners\n• Media visibility on MIT platforms',
 '$10,000 - $150,000', 'Individual or team', 'active'),

('competition', 'Africa Business Heroes Prize Competition',
 'Jack Ma Foundation / Alibaba Philanthropy',
 'Entrepreneurship & Business',
 'Africa Business Heroes (ABH) is a philanthropic initiative by Jack Ma and Alibaba aimed at celebrating and supporting Africa''s most inspiring entrepreneurs. The annual competition selects 10 finalists who share a prize of $1.5 million in total funding. More than a prize, ABH is a platform where entrepreneurs can sharpen their skills, access global networks, and inspire millions of young Africans. West African entrepreneurs including Liberians have a strong tradition in the competition.',
 'Pan-African (Online)', true,
 '2026-07-31',
 'https://www.africabusinessheroes.org',
 E'• African entrepreneur (citizen of any African country including Liberia)\n• Running a for-profit business for at least 2 years\n• Annual revenues between $20,000 and $2 million\n• Strong social impact alongside business performance\n• English fluency required',
 E'• Share of $1.5 million total prize pool\n• Top prize of $300,000 for #1 winner\n• Access to Alibaba''s global e-commerce and tech ecosystem\n• Media feature across Africa Business Heroes platforms\n• Mentorship from Jack Ma and other global business icons',
 'Share of $1.5 million ($300K top)', 'Individual', 'active'),

('competition', 'ECOWAS Youth Award for Excellence',
 'ECOWAS Commission',
 'Leadership & Community Development',
 'The ECOWAS Commission''s Youth Award for Excellence recognizes outstanding young West Africans who have made significant contributions to their communities and the region. Awards are given in categories including Entrepreneurship, Civic Leadership, Arts & Culture, Sports, and Technology. The award celebrates Liberian youth who are making a positive difference, elevating their profiles and connecting them to regional opportunities.',
 'West Africa (ECOWAS region)', false,
 '2026-09-30',
 'https://www.ecowas.int/youth-award',
 E'• Citizen of any ECOWAS member state (including Liberia)\n• Age 18-35\n• Demonstrated excellence in your chosen category\n• Must be nominated by a registered organization or self-nominate\n• Strong community impact track record',
 E'• Trophy and certificate from ECOWAS Commission\n• Cash award and recognition across 15 West African nations\n• Feature in ECOWAS youth publications and platforms\n• Speaking opportunity at ECOWAS summits\n• Networking with regional leaders',
 'Cash award + Trophy', '1 person', 'active');

-- ─── VOLUNTEER OPPORTUNITIES ─────────────────────────────────────────────────
INSERT INTO opportunities (opportunity_type, title, organizer, category, description, location, is_remote, deadline, application_link, eligibility, benefits, commitment_hours, status) VALUES

('volunteer', 'United Nations Volunteers (UNV) – Liberia',
 'United Nations Volunteers Programme (UNV)',
 'Humanitarian & Development',
 'The United Nations Volunteers Programme deploys volunteers in Liberia to support UN agencies including UNDP, UNICEF, WHO, and others working on health, education, governance, and economic recovery. National UN Volunteers (Liberian citizens) and International UN Volunteers both serve in various Liberian counties. This is one of the most impactful volunteering opportunities for Liberians to serve their own nation through the global UN system with professional recognition.',
 'Monrovia and County Capitals, Liberia', false,
 '2026-12-31',
 'https://www.unv.org/become-volunteer',
 E'• Liberian nationals (for National UN Volunteer positions) or international citizens\n• Minimum age 25\n• Relevant professional qualifications (degree + experience in your field)\n• Strong commitment to the UN''s mission\n• Flexibility to work in remote Liberian counties',
 E'• Monthly living allowance (UNV stipend)\n• UN identity card and legal status\n• Annual leave and medical coverage\n• UN Volunteers Certificate of Service\n• Access to UN career network for future opportunities',
 '12 months (full-time)', 'active'),

('volunteer', 'Peace Corps – Liberia Program',
 'U.S. Peace Corps',
 'Education & Community Development',
 'The Peace Corps has served in Liberia since its program''s reopening, deploying American volunteers in rural communities to work alongside Liberians in education, health, and community economic development. Liberian communities that host Peace Corps Volunteers also have opportunities to serve as counterparts, co-trainers, and community liaisons. Liberian-Americans are especially encouraged to apply to serve their heritage country, and host community members gain significant skills through the program.',
 'Rural Liberia (Various Counties)', false,
 '2026-09-01',
 'https://www.peacecorps.gov/volunteer/country/liberia',
 E'• U.S. citizens (for Peace Corps volunteers) or Liberian counterpart roles\n• Age 18+ (no upper age limit)\n• Minimum bachelor''s degree for most positions\n• English fluency\n• Willingness to live in a rural Liberian community for 27 months',
 E'• Living allowance covering basic needs in placement community\n• Medical and dental coverage\n• $10,000 readjustment allowance upon completion\n• Competitive advantage for U.S. government jobs after service\n• Lifelong cross-cultural skills and friendships',
 '27 months (full-time)', 'active'),

('volunteer', 'VSO – Volunteering in Liberia',
 'Voluntary Service Overseas (VSO, UK)',
 'Health & Education',
 'VSO is one of the world''s leading international development organizations, working through volunteers to create sustainable change in some of the world''s poorest regions. VSO currently places skilled international and local volunteers in Liberia in the health sector (supporting Ministry of Health and hospital systems), education (teacher training and curriculum development), and social inclusion. Liberian nationals can apply as professional volunteers and serve in their own country.',
 'Liberia (Health and Education Facilities)', false,
 '2026-08-31',
 'https://www.vsointernational.org/volunteering',
 E'• Professional qualifications in health, education, or social work (or equivalent experience)\n• Liberian nationals and international candidates welcome\n• Commitment to development values\n• Ability to work in under-resourced settings\n• Health clearance required',
 E'• Flights (for international volunteers)\n• Accommodation and living expenses covered\n• Pre-departure training\n• In-country support from VSO team\n• VSO Certificate of Service and professional reference',
 '6-24 months', 'active'),

('volunteer', 'Teach For Liberia – Community Teaching Programme',
 'Ministry of Education, Republic of Liberia / NGO Partners',
 'Education & Youth Development',
 'Teach For Liberia addresses the severe teacher shortage in Liberian rural and peri-urban areas by placing motivated university graduates and professionals in classrooms across the country. Volunteer teachers serve in primary and secondary schools in underserved communities, using innovative teaching methods and mentorship to improve learning outcomes. This program is vital to transforming Liberia''s education system and is supported by international NGOs and the Government of Liberia.',
 'Rural and Peri-Urban Schools, Liberia', false,
 '2026-06-15',
 'https://www.moe.gov.lr/teach-liberia',
 E'• Liberian citizen or diaspora member willing to relocate\n• Minimum bachelor''s degree in any field\n• Passion for education and youth development\n• Ability to commit to one full academic year\n• Basic computer literacy an advantage',
 E'• Monthly teaching stipend from partner organizations\n• Training in modern teaching methods\n• Accommodation support in placement community\n• Certificate from Ministry of Education\n• Strong career reference and competitive advantage for education sector jobs',
 '1 academic year (full-time)', 'active'),

('volunteer', 'All Hands and Hearts – Disaster Response, Liberia',
 'All Hands and Hearts Smart Response',
 'Disaster Response & Community Rebuilding',
 'All Hands and Hearts is an internationally recognized disaster response organization that mobilizes volunteers to rebuild communities affected by natural disasters and chronic poverty. The organization has active programs in West Africa and responds to flooding, displacement, and infrastructure failure in Liberia. Volunteers work directly on construction, rehabilitation, and community development projects. Liberian nationals are welcomed as local volunteer leaders.',
 'Various Liberian Counties (Flood-Prone Areas)', false,
 '2026-12-31',
 'https://www.allhandsandhearts.org/volunteer',
 E'• Age 18+\n• Physical ability to engage in construction/manual work\n• Open to all nationalities; Liberians especially welcome\n• Minimum 2-week commitment\n• No professional qualifications required',
 E'• Hands-on construction and community development experience\n• Certificate of service\n• Meals and accommodation provided during deployment\n• Training in disaster response protocols\n• International volunteer network connections',
 '2 weeks to 6 months (flexible)', 'active');

-- ─── STUDY ABROAD ────────────────────────────────────────────────────────────
INSERT INTO opportunities (opportunity_type, title, organizer, category, description, location, is_remote, deadline, application_link, eligibility, benefits, destination_country, duration, status) VALUES

('study_abroad', 'Fulbright Foreign Student Program',
 'U.S. Department of State / Institute of International Education (IIE)',
 'Graduate Study & Research',
 'The Fulbright Foreign Student Program offers Liberian students, scholars, and professionals the opportunity to pursue graduate degrees or conduct research in the United States. One of the world''s most prestigious academic exchanges, the Fulbright Program is fully funded by the U.S. government and has produced 40 heads of state, 60 Nobel Prize laureates, and thousands of global leaders. Liberians in all fields including STEM, social sciences, law, medicine, and the arts are encouraged to apply.',
 'United States (400+ universities)', false,
 '2026-11-15',
 'https://foreign.fulbrightonline.org',
 E'• Liberian citizen currently residing in Liberia\n• Bachelor''s degree or equivalent (for master''s programs)\n• Master''s degree (for doctoral programs)\n• English proficiency (TOEFL/IELTS required)\n• Commitment to return to Liberia after completing studies\n• Strong leadership potential and community engagement',
 E'• Full tuition and fees at U.S. university\n• Monthly living stipend\n• Round-trip international airfare\n• Health insurance\n• Accident insurance\n• Book and equipment allowance\n• Access to the worldwide Fulbright alumni network',
 'United States', '1-2 years (Master''s or PhD)', 'active'),

('study_abroad', 'Chevening Scholarship – Study in the United Kingdom',
 'UK Government / Foreign, Commonwealth & Development Office (FCDO)',
 'Graduate Study',
 'Chevening is the UK government''s flagship international scholarship program, offering full funding for talented and ambitious Liberians to pursue a one-year master''s degree in the United Kingdom. Since 1983, Chevening has supported over 50,000 scholars from 160 countries. The scholarship targets future Liberian leaders who have demonstrated their potential to make a positive impact back in their home country. All subjects and all UK universities are eligible.',
 'United Kingdom', false,
 '2026-11-05',
 'https://www.chevening.org/scholarships/who-can-apply/liberia',
 E'• Liberian citizen\n• Two years of work experience\n• Eligible to return to Liberia for at least 2 years after completing the scholarship\n• Undergraduate degree and eligible for a UK master''s program\n• English proficiency\n• Applied to 3 different UK university courses',
 E'• Full tuition fees paid directly to UK university\n• Monthly stipend for living expenses in the UK\n• Return economy class airfare\n• Arrival and departure allowances\n• Thesis/dissertation grant\n• Access to the Chevening global alumni network (50,000+)',
 'United Kingdom', '1 year (Master''s degree)', 'active'),

('study_abroad', 'MasterCard Foundation Scholars Program',
 'MasterCard Foundation',
 'Undergraduate & Graduate Study',
 'The MasterCard Foundation Scholars Program provides transformative and high-quality education, combined with academic and leadership development and access to networks, to talented young Africans from economically disadvantaged backgrounds. Partner universities across Africa, North America, and Europe welcome Liberian scholars. The program targets young Africans who demonstrate academic excellence and a commitment to serve their home communities after graduation.',
 'Africa, USA, Canada, UK', false,
 '2026-02-28',
 'https://mastercardfdn.org/programs/scholars-program',
 E'• African student (including Liberian nationals)\n• From an economically disadvantaged background\n• Demonstrated academic excellence\n• Commitment to "give back" and support African development after graduation\n• Applying to a MasterCard Foundation partner university\n• Leadership potential',
 E'• Full tuition and university fees\n• Accommodation, meals, and transport to campus\n• Living stipend and personal needs allowance\n• Textbooks and academic supplies\n• Mentorship, leadership, and career development programs\n• Alumni network for lifelong professional connections',
 'Africa, USA, Canada, UK', 'Full undergraduate or graduate program', 'active'),

('study_abroad', 'DAAD Scholarship – Study in Germany',
 'German Academic Exchange Service (DAAD)',
 'Graduate Study & Research',
 'The German Academic Exchange Service (DAAD) offers a range of scholarships for Liberian students and researchers to study and conduct research in Germany. Germany has excellent universities with no or low tuition fees, world-class research facilities, and a strong commitment to development. DAAD programs cover bachelor, master, doctoral, and post-doctoral levels. Special programs target Liberians working in development-related fields such as engineering, agriculture, environmental science, and public health.',
 'Germany', false,
 '2026-10-15',
 'https://www.daad.de/en/study-and-research-in-germany/scholarships',
 E'• Liberian or other West African citizens\n• Bachelor''s degree (for master''s scholarships)\n• Relevant work experience in development-related fields\n• English or German language proficiency (depending on program)\n• Strong academic record\n• Clear study plan and motivation',
 E'• Monthly stipend (€934 for graduates, €1,200 for PhD students)\n• Travel subsidy\n• Health, accident, and liability insurance\n• German language course allowance\n• Rent subsidy\n• Family subsidy if applicable',
 'Germany', '1-4 years', 'active'),

('study_abroad', 'Erasmus Mundus Joint Master Degrees (Europe)',
 'European Commission / Erasmus+',
 'Master''s Study (Multi-Country)',
 'Erasmus Mundus Joint Master Degrees offer highly competitive full scholarships for outstanding students worldwide including Liberians to pursue internationally integrated master''s programs across multiple European universities. Students study in 2-3 European countries over their 1-2 year master''s degree, gaining a truly international academic and cultural experience. Programs are available across all disciplines including engineering, business, environmental science, social sciences, and digital technologies.',
 'Multiple EU Countries (France, Germany, Netherlands, Spain, etc.)', false,
 '2026-01-31',
 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
 E'• Open to all nationalities globally including Liberia\n• Bachelor''s degree relevant to the chosen master''s program\n• English proficiency (IELTS/TOEFL or equivalent)\n• Motivation letter and letters of recommendation\n• Strong academic record\n• Applications submitted per specific program requirements',
 E'• Full tuition for entire program (paid to all partner universities)\n• Monthly contribution for living and travel expenses (€1,000-€1,400/month)\n• Travel, installation, and visa costs covered\n• Study in 2-3 European countries\n• Prestigious EU-recognized double or multiple degree',
 'Multiple European Countries', '1-2 years (Master''s degree)', 'active'),

('study_abroad', 'YALI Network – U.S. Online and Exchange Programs',
 'Young African Leaders Initiative (YALI) / U.S. Department of State',
 'Leadership & Professional Development',
 'The YALI Network offers Liberians two powerful pathways: free online courses through the YALI Network Online Campus (Coursera-based) covering leadership, civic engagement, business, and technology; and Regional Leadership Centers in West Africa (Accra, Ghana) for in-person training. Additionally, YALI Washington Fellowships, Exchange Programs, and Civic Leadership Forums bring exceptional Liberians to the United States. The YALI Network has 500,000+ members across Sub-Saharan Africa.',
 'USA + YALI Regional Center, Accra (West Africa)', false,
 '2026-09-30',
 'https://yali.state.gov',
 E'• Sub-Saharan African citizen age 18-35\n• Leadership potential in your community\n• English proficiency\n• Online courses: No requirements (free and open)\n• In-person programs and exchanges: Competitive application required\n• U.S. Exchange Programs: Minimum 2 years work or volunteer experience',
 E'• Free access to 100+ online leadership and professional development courses\n• YALI Network certifications\n• For in-person programs: accommodation, meals, and training fully covered\n• U.S. exchange: Fully funded travel, accommodation, and university partnerships\n• 500,000+ member professional network across Africa',
 'United States + West Africa', 'Online (self-paced) or 6-week in-person programs', 'active');

-- ─── RESEARCH OPPORTUNITIES ──────────────────────────────────────────────────
INSERT INTO opportunities (opportunity_type, title, organizer, category, description, location, is_remote, deadline, application_link, eligibility, benefits, research_field, status) VALUES

('research', 'CODESRIA Research Grants – African Social Sciences',
 'Council for the Development of Social Science Research in Africa (CODESRIA)',
 'Social Sciences & Humanities',
 'CODESRIA is Africa''s most important social science research organization, based in Dakar, Senegal. It offers competitive research grants to African scholars studying issues relevant to Africa''s development, governance, and social transformation. Grant programs include Small Grants, National Working Groups, Multinational Working Groups, and the CODESRIA Doctoral and Post-Doctoral Fellowships. Liberian researchers and academics working on governance, conflict transformation, land rights, or Liberian economic development are strongly encouraged to apply.',
 'Dakar, Senegal (Pan-African focus)', true,
 '2026-02-28',
 'https://www.codesria.org/spip.php?article36',
 E'• African scholar or researcher (including Liberians)\n• Affiliated with an African university or research institution\n• Working on research relevant to African social sciences\n• PhD in progress or completed for senior grants\n• Commitment to publish and share research outcomes\n• English or French language proficiency',
 E'• Research grants of $10,000 - $30,000\n• Conference participation funding\n• Publication support in CODESRIA journals\n• Connection to pan-African research networks\n• Academic mentorship from senior scholars\n• Access to CODESRIA library and databases',
 'Social Sciences, Governance, Economics, History', 'active'),

('research', 'NIH Fogarty International Center – Global Health Research',
 'National Institutes of Health (NIH), USA / Fogarty International Center',
 'Health & Biomedical Research',
 'The NIH Fogarty International Center supports global health research and research training, focusing on low- and middle-income countries. Fogarty funds collaborative research between U.S. institutions and institutions in countries like Liberia, particularly in infectious diseases, maternal and child health, mental health, and health system strengthening. Liberian public health professionals, medical researchers, and biomedical scientists are eligible for research training awards and collaborative grants.',
 'USA + Liberia (Collaborative)', true,
 '2026-04-15',
 'https://www.fic.nih.gov/Funding/Pages/default.aspx',
 E'• Health or biomedical researcher from a low/middle-income country (including Liberia)\n• MD, PhD, or equivalent degree or in progress\n• Affiliated with a Liberian institution (Ministry of Health, University of Liberia, research institute)\n• Willingness to work collaboratively with U.S. partner institution\n• English proficiency',
 E'• Research training stipend for extended study at U.S. institutions\n• Return airfare and insurance\n• Collaborative research funding\n• Access to NIH''s world-class laboratories and faculty\n• Co-authorship on research publications\n• Career development in global health research',
 'Public Health, Infectious Disease, Biomedical Sciences', 'active'),

('research', 'TWAS Research Grants – Developing World Scientists',
 'The World Academy of Sciences (TWAS)',
 'Natural Sciences & Agriculture',
 'The World Academy of Sciences (TWAS) supports scientific capacity in the developing world through research grants for scientists in countries with relatively underdeveloped science capacity, including Liberia. TWAS grants are available for research in biology, chemistry, mathematics, physics, earth sciences, agriculture, and medicine. The program is designed to help Liberian scientists conduct cutting-edge research using locally available resources, contributing to scientific knowledge and national development.',
 'Trieste, Italy (Global programs)', true,
 '2026-03-31',
 'https://twas.org/opportunity/twas-research-grants',
 E'• Citizen of a developing country and working in that country (including Liberia)\n• PhD in natural sciences or agricultural sciences\n• Employed by a research institution in Liberia\n• Maximum age 45 for grants\n• Demonstrated publication record or strong research proposal\n• Working in an underequipped laboratory',
 E'• Research grants of up to $15,000\n• Equipment and supplies for laboratory research\n• TWAS mentorship from leading world scientists\n• Visibility in international scientific community\n• Membership consideration in TWAS network',
 'Natural Sciences, Agriculture, Medicine, Chemistry', 'active'),

('research', 'African Academy of Sciences (AAS) – AESA Research Grants',
 'African Academy of Sciences (AAS)',
 'Health, Agriculture & Environment',
 'The Alliance for Accelerating Excellence in Science in Africa (AESA), housed at the African Academy of Sciences, funds African researchers to develop breakthrough solutions to Africa''s most pressing health, agricultural, and environmental challenges. AESA programs like the DELTAS Africa Initiative, ARISE, and Grand Challenges Africa have invested over $100 million in African science. Liberian researchers at universities and research institutions are strongly encouraged to apply across all program tracks.',
 'Nairobi, Kenya (Pan-African)', true,
 '2026-06-30',
 'https://www.aasciences.africa/aesa',
 E'• African researcher or scientist (including Liberians)\n• PhD or MD with research focus\n• Affiliated with an African research institution or university\n• Strong research proposal addressing African health, agriculture, or environmental challenges\n• Track record of publications or strong early-career justification\n• Commitment to capacity building within Africa',
 E'• Research grants ranging from $10,000 to $500,000\n• Capacity-building support for teams and institutions\n• Training and fellowships within Africa\n• Connection to global science funding networks\n• Publication and communication support',
 'Health, Agriculture, Environment, Biotechnology', 'active'),

('research', 'International Foundation for Science (IFS) – Early Career Research Grant',
 'International Foundation for Science (IFS, Stockholm)',
 'Natural Resources & Food Security',
 'The International Foundation for Science supports early-career researchers in developing countries with individual research grants in the natural and social sciences. IFS particularly supports research in water and sanitation, food production systems, natural resources management, and the biological sciences — areas highly relevant to Liberia''s development. IFS grants come with advisory support from international scientists, making them a unique combination of funding and mentorship.',
 'Stockholm, Sweden (Global programs)', true,
 '2026-05-31',
 'https://www.ifs.se/grants',
 E'• Researcher from a developing country including Liberia\n• Engaged in research in natural or social sciences\n• Under 40 years old\n• Affiliated with a recognized research institution in your home country\n• PhD (or equivalent, with track record)\n• Research focus on developing country priorities',
 E'• Research grants of $15,000 - $20,000\n• International scientific advisory support\n• Connection to IFS''s global developing-country researcher network\n• Travel grants to attend scientific conferences\n• Facilitation of institutional partnerships',
 'Water Resources, Food Production, Natural Sciences, Agriculture', 'active'),

('research', 'Liberia Institute of Statistics (LISGIS) – Research Partnership Programme',
 'LISGIS (Liberia Institute of Statistics and Geo-Information Services)',
 'Data Science & National Statistics',
 'LISGIS, the Government of Liberia''s official statistical agency, offers research partnership opportunities for Liberian academics, data scientists, and researchers to collaborate on national surveys, census data analysis, and economic research. Partner researchers gain access to Liberia''s national datasets — including household income surveys, census data, and economic indicators — and work alongside LISGIS staff on publications and policy briefs that directly inform government planning and development programs.',
 'Monrovia, Liberia', false,
 '2026-07-31',
 'https://www.lisgis.net/research-partnerships',
 E'• Liberian nationals preferred; international researchers with Liberia focus welcome\n• Advanced degree in statistics, economics, demography, or data science\n• Affiliated with a Liberian or international research institution\n• Clear research proposal using Liberian national data\n• Commitment to produce publishable outputs',
 E'• Access to national datasets and LISGIS databases\n• Collaborative publication opportunities\n• LISGIS workspace and technical support\n• Policy engagement with Government of Liberia\n• Certificate of partnership and professional recognition',
 'Statistics, Economics, Demography, Data Science, Public Policy', 'active');

-- Done: 31 opportunities seeded across all 6 types
