import { NextRequest, NextResponse } from "next/server";
import { insforge } from "@/lib/insforge";
import { checkProAccess } from "@/lib/checkProAccess";
export const runtime = "nodejs";

const GROQ_MODEL = "llama-3.3-70b-versatile";

let _cachedKey: string | null = null;
async function getGroqKey(): Promise<string> {
  if (process.env.GROQ_API_KEY) return process.env.GROQ_API_KEY;
  if (_cachedKey) return _cachedKey;
  try {
    const { data } = await insforge.database
      .from("settings")
      .select("value")
      .eq("key", "groq_api_key")
      .single();
    _cachedKey = (data as any)?.value ?? "";
    return _cachedKey!;
  } catch {
    return "";
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { jobTitle, companyName, cvText, userId } = body;

    if (!jobTitle || !companyName || !userId) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // Pro check
    const isPro = await checkProAccess(userId);
    if (!isPro) {
      return NextResponse.json({ error: "Pro subscription required", code: "PRO_REQUIRED" }, { status: 403 });
    }

    const apiKey = await getGroqKey();
    if (!apiKey) {
      return NextResponse.json({ error: "AI service not configured" }, { status: 500 });
    }

    const { writingMode, industry, country } = body;
    const mode = (writingMode || "professional").toLowerCase().replace(" ", "_");

    // ── Writing mode configurations ──────────────────────────────────────────
    const modeInstructions: Record<string, string> = {
      professional: `Direct, confident, polished but not stiff. Think senior colleague writing to a peer. Short sentences where they matter. Evidence over adjectives.`,
      casual_professional: `Warm and personable — smart person who doesn't need to perform but is genuinely serious. Conversational rhythm without being informal.`,
      confident: `Lead with the strongest claim immediately. No hedging. Assertive but not arrogant. Show track record, not hope.`,
      creative: `Open with something unexpected — a specific observation, a brief story, an unusual angle. Use vivid concrete language. Show personality.`,
      technical: `Precise and evidence-based. Prioritize metrics, tools, outcomes. No filler. Every sentence earns its place.`,
      student: `Honest about being early-career but leads with potential. Emphasize learning speed, projects, fresh perspective. No apology for inexperience.`,
    };

    const systemPrompt = `You are a skilled career writer. Your job is to write personalized, authentic application letters that read like they were written by a real person — not generated by AI.

WRITING MODE: ${mode.toUpperCase().replace("_", " ")}
${modeInstructions[mode] || modeInstructions.professional}

ABSOLUTELY FORBIDDEN — NEVER USE THESE:
× "I am writing to express"
× "I am excited to apply" or any close variation
× "In conclusion" / "To conclude"
× "Furthermore" / "Moreover" / "Additionally" / "In addition"
× "I believe my skills align"
× "I am a strong candidate" / "I am confident that"
× "Thank you for considering my application"
× "Please do not hesitate to contact"
× "I would be delighted" / "I would welcome the opportunity"
× Starting three consecutive sentences with "I"
× Uniform paragraph lengths (all paragraphs same size)
× "synergy", "leverage", "dynamic", "results-driven", "passionate about"
× "My name is [X] and I am applying for"
× "This position caught my eye"

WHAT MAKES THIS LETTER WORK:
✓ Varies sentence length — mix short punchy with longer flowing
✓ At least 2 sentences start with something other than "I"
✓ One specific detail showing genuine knowledge of role or company
✓ Active verbs: built, led, ran, created, fixed, shipped, improved
✓ Closing feels like a natural end to a real conversation
✓ Draws from CV to tell a mini-story, not list skills mechanically
✓ Reads like a thoughtful person wrote it quickly and well

STRUCTURE: 3-4 paragraphs. No rigid formula. Let the story determine the shape.
Opening: A direct statement, brief context, or specific relevant observation — NOT "I am writing..."
Body: Weave 1-2 experiences from the CV into context naturally, not as a bullet list.
Closing: Simple, direct, natural. No formal sign-off formula.

OUTPUT: Return ONLY the letter text. Start directly with the greeting. Use [Your Name], [Your Email], [Your Phone] placeholders. No JSON, no preamble, no commentary.`;

    const contextLines = [
      `Position: ${jobTitle}`,
      `Company: ${companyName}`,
      industry ? `Industry: ${industry}` : null,
      country ? `Country: ${country}` : null,
    ].filter(Boolean).join("\n");

    const cvSection = cvText?.trim()
      ? `\n\nAPPLICANT BACKGROUND (weave naturally into the letter — do not list):\n${cvText.slice(0, 4000)}`
      : "\n\nNo CV provided. Write a compelling general letter focused on transferable skills and genuine interest.";

    const userPrompt = `Write a natural, human-sounding application letter.\n\n${contextLines}${cvSection}\n\nWrite the letter now. Start with the greeting.`;

    // Pass 1 — Generate
    const groqRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: GROQ_MODEL,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.78,
        max_tokens: 1400,
        stream: false,
      }),
    });

    if (!groqRes.ok) {
      return NextResponse.json({ error: "AI failed to generate letter" }, { status: 500 });
    }

    const groqData = await groqRes.json();
    let letterContent: string = groqData?.choices?.[0]?.message?.content ?? "";

    // Pass 2 — Humanization layer (second AI call)
    if (letterContent) {
      try {
        const humanRes = await fetch("https://api.groq.com/openai/v1/chat/completions", {
          method: "POST",
          headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            model: GROQ_MODEL,
            messages: [{
              role: "user",
              content: `You are an editor who makes writing sound authentically human. Improve this application letter by:
1. Removing any remaining AI-sounding phrases or robotic transitions
2. Breaking up any uniform rhythm — vary sentence lengths more
3. Making the voice feel more natural, personal, and direct
4. Ensuring no two consecutive paragraphs follow the same pattern
Return ONLY the improved letter. No explanations.\n\n${letterContent}`,
            }],
            temperature: 0.72,
            max_tokens: 1400,
            stream: false,
          }),
        });
        if (humanRes.ok) {
          const hd = await humanRes.json();
          letterContent = hd?.choices?.[0]?.message?.content || letterContent;
        }
      } catch { /* fall back to original */ }
    }

    if (!letterContent) {
      return NextResponse.json({ error: "Empty response from AI" }, { status: 500 });
    }

    // Save to application_letters
    const { data: letterData, error: letterError } = await insforge.database
      .from("application_letters")
      .insert([{
        user_id: userId,
        job_title: jobTitle,
        company_name: companyName,
        letter_content: letterContent,
      }])
      .select("id")
      .single();

    if (letterError) {
      console.error("Letter save error:", letterError);
    }

    return NextResponse.json({
      letterId: (letterData as any)?.id ?? null,
      content: letterContent,
    });
  } catch (err: any) {
    console.error("Letter API error:", err);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
